// src/app/footer.tsx
// SPDX-FileCopyrightText: 2024 PNED G.I.E.
//
// SPDX-License-Identifier: Apache-2.0

"use client";

import {
  faGithub,
  faLinkedin,
  faXTwitter,
} from "@fortawesome/free-brands-svg-icons";
import { faGlobe } from "@fortawesome/free-solid-svg-icons";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";

import Image from "next/image";
import flag from "../public/eu-flag.png";

function Footer() {
  return (
    <footer className="flex flex-col items-center justify-between gap-y-4 border-t-4 border-t-primary bg-white-smoke p-7 md:flex-row md:gap-x-4 md:gap-y-0">
      <div className="flex items-center gap-4">
        <Image src={flag} alt="EU flag" width={80} />
        <p className="text-xs md:text-sm">
          GDI project receives funding from the European Union’s Digital Europe
          <br />
          Programme under grant agreement number 101081813.
        </p>
      </div>

      <div className="flex flex-col gap-2">
        <div className="flex flex-row justify-center gap-11 text-primary">
          <a
            href="https://www.linkedin.com/company/gdi-euproject/"
            target="_blank"
            rel="noopener"
            className="hover:text-info"
          >
            <FontAwesomeIcon
              icon={faLinkedin}
              className="text-lg md:text-2xl"
            />
          </a>
          <a
            color="primary"
            href="https://twitter.com/GDI_EUproject"
            target="_blank"
            rel="noopener"
            className="hover:text-info"
          >
            <FontAwesomeIcon
              icon={faXTwitter}
              className="text-lg md:text-2xl"
            />
          </a>
          <a
            color="primary"
            href="https://github.com/GenomicDataInfrastructure"
            target="_blank"
            rel="noopener"
            className="hover:text-info"
          >
            <FontAwesomeIcon icon={faGithub} className="text-lg md:text-2xl" />
          </a>
          <a
            color="primary"
            href="https://gdi.onemilliongenomes.eu/"
            target="_blank"
            rel="noopener"
            className="hover:text-info"
          >
            <FontAwesomeIcon icon={faGlobe} className="text-lg md:text-2xl" />
          </a>
        </div>
        <a
          className="text-xs hover:text-info md:text-left md:text-sm"
          href="mailto:gdi-coordination@elixir-europe.org"
        >
          gdi-coordination&#64;elixir-europe.org
        </a>
      </div>
    </footer>
  );
}

export default Footer;

// src/app/components/footer/footer.component.ts
import { Component } from '@angular/core';
import { MatIconRegistry } from '@angular/material/icon';
import { DomSanitizer } from '@angular/platform-browser';
import { faLinkedin, faXTwitter, faGithub } from '@fortawesome/free-brands-svg-icons';
import { faGlobe } from '@fortawesome/free-solid-svg-icons';
import { faExclamationCircle } from '@fortawesome/free-solid-svg-icons';

@Component({
  selector: 'app-footer',
  templateUrl: './footer.component.html',
  styleUrls: ['./footer.component.scss'],
})
export class FooterComponent {
  faLinkedin = faLinkedin;
  faGithub = faGithub;
  faXTwitter = faXTwitter;
  faGlobe = faGlobe;
  faExclamationCircle = faExclamationCircle;

  constructor(private matIconRegistry: MatIconRegistry, private domSanitizer: DomSanitizer) {
    this.matIconRegistry.addSvgIcon(
      'linkedin',
      this.domSanitizer.bypassSecurityTrustResourceUrl('../../assets/linkedin.svg')
    );
  }
}

<!--
SPDX-FileCopyrightText: 2024 Stichting Health-RI
SPDX-FileContributor: PNED G.I.E.

SPDX-License-Identifier: Apache-2.0
-->

<div
  class="m-5 mt-20 md:mt-15 p-5 bg-claret text-white rounded-lg flex flex-row gap-4 items-center"
>
  <div class="text-2xl">
    <fa-icon [icon]="faExclamationCircle"></fa-icon>
  </div>
  <div class="text-[14px] text-pretty">
    Please note that this version of GDI User Portal is the result of
    deliverable "MS11 - Development of the user portal deployed", which is still
    undergoing further feature developments and testing before its release in
    production. Therefore, you may witness some instabilities and broken links.
    Should you have any feedback, please let us know so we can take into account
    for the future releases accordingly. Your help in this regard is greatly
    appreciated!
  </div>
</div>
<div
  class="border-t-4 border-[#7B1C58] text-sm flex flex-col md:flex-row justify-between p-4 gap-2 items-center md:space-y-0 md:space-x-4 bg-[#f5f5f5]"
>
  <div class="flex items-center gap-4">
    <img src="/assets/eu-flag.png" alt="EU flag" width="80" />
    <p class="text-sm">
      GDI project receives funding from the European Union’s Digital Europe
      <br />
      Programme under grant agreement number 101081813.
    </p>
  </div>

  <div class="flex flex-col">
    <div class="flex flex-row gap-4">
      <a
        mat-icon-button
        color="primary"
        href="https://www.linkedin.com/company/gdi-euproject/"
        target="_blank"
        rel="noopener"
      >
        <fa-icon [icon]="faLinkedin"></fa-icon>
      </a>
      <a
        mat-icon-button
        color="primary"
        href="https://twitter.com/GDI_EUproject"
        target="_blank"
        rel="noopener"
      >
        <fa-icon [icon]="faXTwitter"></fa-icon>
      </a>
      <a
        mat-icon-button
        color="primary"
        href="https://github.com/GenomicDataInfrastructure"
        target="_blank"
        rel="noopener"
      >
        <fa-icon [icon]="faGithub"></fa-icon>
      </a>
      <a
        mat-icon-button
        color="primary"
        href="https://gdi.onemilliongenomes.eu/"
        target="_blank"
        rel="noopener"
      >
        <fa-icon [icon]="faGlobe"></fa-icon>
      </a>
    </div>
    <a
      class="text-sm text-center md:text-left"
      href="mailto:gdi-coordination@elixir-europe.org"
      >gdi-coordination&#64;elixir-europe.org</a
    >
  </div>
</div>
