// src/app/header.tsx
// SPDX-FileCopyrightText: 2024 PNED G.I.E.
//
// SPDX-License-Identifier: Apache-2.0

"use client";

import Button from "@/components/button";
import { useDatasetBasket } from "@/providers/DatasetBasketProvider";
import { User } from "@/types/user.types";
import { keycloackSessionLogOut } from "@/utils/auth";
import {
  faBars,
  faDatabase,
  faHome,
  faInfoCircle,
  faRightFromBracket,
  faRightToBracket,
  faShoppingCart,
  faUser,
} from "@fortawesome/free-solid-svg-icons";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { signIn, signOut, useSession } from "next-auth/react";
import Image from "next/image";
import Link from "next/link";
import { usePathname } from "next/navigation";
import { useEffect, useState } from "react";
import logo from "../public/egdi-logo-horizontal-full-color-rgb.svg";
import Avatar from "./avatar";
import Notification from "./notification";

function Header() {
  const { data: session, status } = useSession();
  const [isMenuOpen, setIsMenuOpen] = useState<boolean>(false);
  const activeTab = usePathname();
  const { basket, isLoading } = useDatasetBasket();

  function handleSignOut() {
    keycloackSessionLogOut().then(() => signOut({ callbackUrl: "/" }));
  }

  const closeMenu = () => {
    setIsMenuOpen(false);
  };

  useEffect(() => {
    const handleOutsideClick = (event: MouseEvent) => {
      const targetElement = event.target as Element;
      if (isMenuOpen && !targetElement.closest(".menu-container")) {
        setIsMenuOpen(false);
      }
    };

    window.addEventListener("click", handleOutsideClick);

    return () => {
      window.removeEventListener("click", handleOutsideClick);
    };
  }, [isMenuOpen]);

  let loginBtn;

  if (status !== "loading") {
    loginBtn = session ? (
      <>
        <Notification />
        <Avatar user={session.user as User} />
      </>
    ) : (
      <Button
        icon={faUser}
        text="Login"
        type="primary"
        onClick={() => signIn("keycloak")}
      />
    );
  }

  return (
    <div className="flex w-full items-center justify-between bg-white-smoke px-4">
      <div className="flex justify-between gap-x-12 lg:gap-x-24">
        <Link href="/">
          <Image
            src={logo}
            alt="Logo"
            className="mb-4 mt-4"
            width="190"
            height="69"
          />
        </Link>
        <div className="hidden items-center gap-x-3 text-base font-semibold text-primary sm:flex md:text-lg">
          <Link
            href="/"
            className={`rounded-lg border-[1.5px] border-white-smoke px-3 py-1 transition-colors duration-300 hover:border-primary hover:shadow-sm md:px-7 ${activeTab === "/" ? "bg-primary text-white" : ""}`}
          >
            Home
          </Link>
          <Link
            href="/datasets"
            className={`rounded-lg border-[1.5px] border-white-smoke px-3 py-1 transition-colors duration-300 hover:border-primary hover:shadow-sm md:px-7 ${activeTab.includes("datasets") ? "bg-primary text-white" : ""}`}
          >
            Datasets
          </Link>
          <Link
            href="/about"
            className={`rounded-lg border-[1.5px] border-white-smoke px-3 py-1 transition-colors duration-300 hover:border-primary hover:shadow-sm md:px-7 ${activeTab === "/about" ? "bg-primary text-white" : ""}`}
          >
            About
          </Link>
        </div>
      </div>
      <div className="mr-3 hidden items-center gap-x-5 sm:flex md:gap-x-8">
        {!isLoading && (
          <Link
            href="/basket"
            className="relative flex items-center text-info hover:text-primary"
          >
            <FontAwesomeIcon icon={faShoppingCart} size="lg" />
            {basket.length > 0 && (
              <span className="absolute right-0 top-0 inline-flex -translate-y-1/2 translate-x-1/2 transform items-center justify-center rounded-full bg-primary px-2 py-1 text-xs font-bold leading-none text-red-100">
                {basket.length}
              </span>
            )}
          </Link>
        )}
        {loginBtn}
      </div>

      <div className="menu-container relative sm:hidden">
        <button
          onClick={() => setIsMenuOpen(!isMenuOpen)}
          className="text-primary focus:outline-none"
        >
          <FontAwesomeIcon icon={faBars} className="text-xl" />
        </button>
        {isMenuOpen && (
          <div className="absolute right-0 mt-2 w-48 origin-top-right rounded-md bg-white shadow-lg">
            <Link
              href="/"
              className="block px-4 py-2 hover:bg-primary hover:text-white"
              onClick={closeMenu}
            >
              <FontAwesomeIcon icon={faHome} className="mr-2" />
              Home
            </Link>
            <Link
              href="/datasets"
              className="block px-4 py-2 hover:bg-primary hover:text-white"
              onClick={closeMenu}
            >
              <FontAwesomeIcon icon={faDatabase} className="mr-2" />
              Datasets
            </Link>
            <Link
              href="/about"
              className="block px-4 py-2 hover:bg-primary hover:text-white"
              onClick={closeMenu}
            >
              <FontAwesomeIcon icon={faInfoCircle} className="mr-2" />
              About
            </Link>
            <Link
              href="/basket"
              className="block px-4 py-2 hover:bg-primary hover:text-white"
              onClick={closeMenu}
            >
              <FontAwesomeIcon icon={faShoppingCart} className="mr-2" />
              {isLoading ? "Basket" : `Basket (${basket.length})`}
            </Link>
            {session && (
              <div className="border-b border-gray-200 px-4 py-2">
                <FontAwesomeIcon icon={faUser} className="mr-2" />
                {session?.user?.name}
              </div>
            )}
            {!session && (
              <button
                onClick={() => signIn("keycloak")}
                className="block w-full px-4 py-2 text-left hover:bg-primary hover:text-white"
              >
                <FontAwesomeIcon icon={faRightToBracket} className="mr-2" />
                Login
              </button>
            )}
            {session && (
              <button
                onClick={handleSignOut}
                className="block w-full px-4 py-2 text-left hover:bg-primary hover:text-white"
              >
                <FontAwesomeIcon icon={faRightFromBracket} className="mr-2" />
                Logout
              </button>
            )}
          </div>
        )}
      </div>
    </div>
  );
}

export default Header;

// src/app/components/header/header.component.ts
// SPDX-FileCopyrightText: 2024 Stichting Health-RI
// SPDX-FileContributor: PNED G.I.E.
//
// SPDX-License-Identifier: Apache-2.0

import { Component, OnInit } from '@angular/core';
import { OidcSecurityService, LoginResponse } from 'angular-auth-oidc-client';
import { faUser, faRightToBracket, faRightFromBracket, faBars } from '@fortawesome/free-solid-svg-icons';

@Component({
  selector: 'app-header',
  templateUrl: './header.component.html',
  styleUrls: ['./header.component.scss'],
})
export class HeaderComponent implements OnInit {
  isAuthenticated = false;
  userData: any;
  faUser = faUser;
  faRightToBracket = faRightToBracket;
  faRightFromBracket = faRightFromBracket;
  faBars = faBars;

  constructor(private readonly oidcSecurityService: OidcSecurityService) {}

  ngOnInit() {
    this.oidcSecurityService.checkAuth().subscribe((loginResponse: LoginResponse) => {
      const { isAuthenticated, userData } = loginResponse;
      this.isAuthenticated = isAuthenticated;
      this.userData = userData;
    });
  }

  login() {
    this.oidcSecurityService.authorize();
  }

  logout() {
    this.oidcSecurityService.logoffAndRevokeTokens().subscribe(({ isAuthenticated, userData }) => {
      this.isAuthenticated = isAuthenticated;
      this.userData = userData;
    });
  }

  username() {
    return this.userData?.preferred_username;
  }
}

<div class="flex flex-row items-center bg-[#f5f5f5] pl-4 pr-4 text-lg relative">
  <a
    routerLink="/"
    routerLinkActive="active-router"
    [routerLinkActiveOptions]="{ exact: true }"
  >
    <img
      src="/assets/egdi-logo-horizontal-full-color-rgb.svg"
      alt="Logo"
      class="mt-4 mb-4"
      width="190"
    />
  </a>

  <span class="grow"></span>
  <div class="flex flex-col items-center">
    <div
      class="hidden sm:flex flex-row gap-2 items-center justify-end w-full text-sm mb-3"
    >
      <fa-icon [icon]="faUser" *ngIf="isAuthenticated"></fa-icon>
      <span *ngIf="isAuthenticated">{{ username() }}</span>
      <a *ngIf="!isAuthenticated" (click)="login()">
        <fa-icon [icon]="faRightToBracket"></fa-icon>
      </a>
      <a *ngIf="isAuthenticated" (click)="logout()">
        <fa-icon [icon]="faRightFromBracket"></fa-icon>
      </a>
    </div>
    <div class="hidden sm:flex flex-row gap-4 items-center">
      <a
        routerLink="/"
        routerLinkActive="active-router"
        [routerLinkActiveOptions]="{ exact: true }"
        >Home</a
      >
      <a routerLink="/datasets" routerLinkActive="active-router">Datasets</a>
      <a routerLink="/about" routerLinkActive="active-router">About</a>
    </div>
    <div class="sm:hidden absolute right-0 z-50 top-8">
      <button
        mat-icon-button
        color="primary"
        class="text-gray-800 focus:outline-none"
        [matMenuTriggerFor]="dropdownMenu"
      >
        <fa-icon [icon]="faBars"></fa-icon>
      </button>
      <mat-menu
        #dropdownMenu="matMenu"
        class="origin-top-right absolute right-0 mt-2 w-48 rounded-md shadow-lg text-xl font-normal"
      >
        <a
          [routerLink]="['/']"
          class="text-gray-800 hover:bg-gray-100 block px-4 py-2"
          routerLinkActive="active-router"
          [routerLinkActiveOptions]="{ exact: true }"
          >Home
        </a>

        <a
          [routerLink]="['/datasets']"
          class="text-gray-800 hover-bg-gray-100 block px-4 py-2"
          routerLinkActive="active-router"
          >Datasets
        </a>

        <a
          [routerLink]="['/about']"
          class="text-gray-800 hover:bg-gray-100 block px-4 py-2"
          routerLinkActive="active-router"
          >About
        </a>

        <div *ngIf="isAuthenticated" class="px-4 py-2 border-b border-gray-200">
          <fa-icon [icon]="faUser" class="mr-2"></fa-icon>
          {{ username() }}
        </div>

        <a
          *ngIf="!isAuthenticated"
          class="text-gray-800 hover:bg-gray-100 block px-4 py-2"
          (click)="login()"
        >
          <fa-icon [icon]="faRightToBracket" class="mr-2"></fa-icon>Login
        </a>
        <a
          *ngIf="isAuthenticated"
          class="text-gray-800 hover:bg-gray-100 block px-4 py-2"
          (click)="logout()"
        >
          <fa-icon [icon]="faRightFromBracket" class="mr-2"></fa-icon>Logout
        </a>
      </mat-menu>
    </div>
  </div>
</div>
