// src/components/PortalStatistics.tsx
// SPDX-FileCopyrightText: 2024 PNED G.I.E.
//
// SPDX-License-Identifier: Apache-2.0
"use client";
import React, { useEffect, useState } from "react";
import { portalStatistics } from "@/services/ckan";
import { PortalStatistics as IPortalStatistics } from "@/services/ckan/types/portalStatistics.types";

export function PortalStatistics() {
  const [propCounters, setPropCounters] = useState<IPortalStatistics | null>(
    null,
  );

  useEffect(() => {
    const fetchData = async () => {
      const data = await portalStatistics();
      setPropCounters(data);
    };

    fetchData();
  }, []);

  if (propCounters === null) {
    return <div>Loading...</div>;
  }

  return (
    <div className="mt-4 px-4">
      <div className="mx-auto max-w-7xl">
        <div className="grid grid-cols-1 gap-20 sm:grid-cols-3 md:grid-cols-3 lg:grid-cols-3 xl:grid-cols-3">
          {Object.entries(propCounters).map(([key, value]) => (
            <div key={key}>
              <div className="rounded-lg bg-white p-4 text-center shadow-md">
                <div className="text-xl font-semibold md:text-2xl">
                  {value.toLocaleString("en-GB")}
                </div>
                <div className="md:text-md mt-2 text-sm">{key}</div>
              </div>
            </div>
          ))}
        </div>
      </div>
    </div>
  );
}

// src/app/components/portal-statistics/portal-statistics.component.ts
import { Component } from '@angular/core';
import { PortalStatistics } from 'src/app/interfaces/portal-statistics';
import { CkanService } from 'src/app/services/ckan.service';

@Component({
  selector: 'app-portal-statistics',
  templateUrl: './portal-statistics.component.html',
  styleUrls: ['./portal-statistics.component.scss'],
})
export class PortalStatisticsComponent {
  portalStatistics!: PortalStatistics;

  constructor(private ckanService: CkanService) {}

  ngOnInit(): void {
    this.ckanService
      .getPortalStatistics()
      .subscribe((response) => (this.portalStatistics = response));
  }
}

<!--
SPDX-FileCopyrightText: 2024 PNED G.I.E.

SPDX-License-Identifier: Apache-2.0
-->

<div class="flex justify-center mt-10">
  <div
    class="grid grid-cols-2 w-full max-w-sm bg-scampi-blue-low-opacity p-6 rounded-md"
  >
    <div *ngFor="let detail of portalStatistics | keyvalue">
      <div class="mb-6">
        <p class="text-4xl font-bold text-scampi-blue text-center text-xl mb-1">
          {{ detail.value }}
        </p>
        <p class="text-lg font-bold text-black text-center text-sm">
          {{ detail.key }}
        </p>
      </div>
    </div>
  </div>
</div>
