// src/app/components/header/header.component.ts
// SPDX-FileCopyrightText: 2024 Stichting Health-RI
// SPDX-FileContributor: PNED G.I.E.
//
// SPDX-License-Identifier: Apache-2.0

import { Component, OnInit } from '@angular/core';
import { OidcSecurityService, LoginResponse } from 'angular-auth-oidc-client';
import { faUser, faRightToBracket, faRightFromBracket, faBars } from '@fortawesome/free-solid-svg-icons';

@Component({
  selector: 'app-header',
  templateUrl: './header.component.html',
  styleUrls: ['./header.component.scss'],
})
export class HeaderComponent implements OnInit {
  isAuthenticated = false;
  userData: any;
  faUser = faUser;
  faRightToBracket = faRightToBracket;
  faRightFromBracket = faRightFromBracket;
  faBars = faBars;

  constructor(private readonly oidcSecurityService: OidcSecurityService) {}

  ngOnInit() {
    this.oidcSecurityService.checkAuth().subscribe((loginResponse: LoginResponse) => {
      const { isAuthenticated, userData } = loginResponse;
      this.isAuthenticated = isAuthenticated;
      this.userData = userData;
    });
  }

  login() {
    this.oidcSecurityService.authorize();
  }

  logout() {
    this.oidcSecurityService.logoffAndRevokeTokens().subscribe(({ isAuthenticated, userData }) => {
      this.isAuthenticated = isAuthenticated;
      this.userData = userData;
    });
  }

  username() {
    return this.userData?.preferred_username;
  }
}

<div class="flex flex-row items-center bg-[#f5f5f5] pl-4 pr-4 text-lg relative">
  <a
    routerLink="/"
    routerLinkActive="active-router"
    [routerLinkActiveOptions]="{ exact: true }"
  >
    <img
      src="/assets/egdi-logo-horizontal-full-color-rgb.svg"
      alt="Logo"
      class="mt-4 mb-4"
      width="190"
    />
  </a>

  <span class="grow"></span>
  <div class="flex flex-col items-center">
    <div
      class="hidden sm:flex flex-row gap-2 items-center justify-end w-full text-sm mb-3"
    >
      <fa-icon [icon]="faUser" *ngIf="isAuthenticated"></fa-icon>
      <span *ngIf="isAuthenticated">{{ username() }}</span>
      <a *ngIf="!isAuthenticated" (click)="login()">
        <fa-icon [icon]="faRightToBracket"></fa-icon>
      </a>
      <a *ngIf="isAuthenticated" (click)="logout()">
        <fa-icon [icon]="faRightFromBracket"></fa-icon>
      </a>
    </div>
    <div class="hidden sm:flex flex-row gap-4 items-center">
      <a
        routerLink="/"
        routerLinkActive="active-router"
        [routerLinkActiveOptions]="{ exact: true }"
        >Home</a
      >
      <a routerLink="/datasets" routerLinkActive="active-router">Datasets</a>
      <a routerLink="/about" routerLinkActive="active-router">About</a>
    </div>
    <div class="sm:hidden absolute right-0 z-50 top-8">
      <button
        mat-icon-button
        color="primary"
        class="text-gray-800 focus:outline-none"
        [matMenuTriggerFor]="dropdownMenu"
      >
        <fa-icon [icon]="faBars"></fa-icon>
      </button>
      <mat-menu
        #dropdownMenu="matMenu"
        class="origin-top-right absolute right-0 mt-2 w-48 rounded-md shadow-lg text-xl font-normal"
      >
        <a
          [routerLink]="['/']"
          class="text-gray-800 hover:bg-gray-100 block px-4 py-2"
          routerLinkActive="active-router"
          [routerLinkActiveOptions]="{ exact: true }"
          >Home
        </a>

        <a
          [routerLink]="['/datasets']"
          class="text-gray-800 hover-bg-gray-100 block px-4 py-2"
          routerLinkActive="active-router"
          >Datasets
        </a>

        <a
          [routerLink]="['/about']"
          class="text-gray-800 hover:bg-gray-100 block px-4 py-2"
          routerLinkActive="active-router"
          >About
        </a>

        <div *ngIf="isAuthenticated" class="px-4 py-2 border-b border-gray-200">
          <fa-icon [icon]="faUser" class="mr-2"></fa-icon>
          {{ username() }}
        </div>

        <a
          *ngIf="!isAuthenticated"
          class="text-gray-800 hover:bg-gray-100 block px-4 py-2"
          (click)="login()"
        >
          <fa-icon [icon]="faRightToBracket" class="mr-2"></fa-icon>Login
        </a>
        <a
          *ngIf="isAuthenticated"
          class="text-gray-800 hover:bg-gray-100 block px-4 py-2"
          (click)="logout()"
        >
          <fa-icon [icon]="faRightFromBracket" class="mr-2"></fa-icon>Logout
        </a>
      </mat-menu>
    </div>
  </div>
</div>

// src/components/header.tsx
// SPDX-FileCopyrightText: 2024 PNED G.I.E.
//
// SPDX-License-Identifier: Apache-2.0
"use client";
import {
  faBars,
  faRightFromBracket,
  faRightToBracket,
  faUser,
} from "@fortawesome/free-solid-svg-icons";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import Image from "next/image";
import Link from "next/link";
import { usePathname } from "next/navigation";
import { useState } from "react";
import logo from "../public/egdi-logo-horizontal-full-color-rgb.svg";

function Header() {
  const [isMenuOpen, setIsMenuOpen] = useState(false);
  const activeTab = usePathname();

  // Mock authentication state and functions
  const isAuthenticated = false;
  const username = () => "User";
  const login = () => console.log("Login");
  const logout = () => console.log("Logout");

  return (
    <div className="flex w-full items-center justify-between bg-white-smoke px-4">
      <Link href="/">
        <Image
          src={logo}
          alt="Logo"
          className="mb-4 mt-4"
          width="190"
          height="69"
        />
      </Link>
      <div className="items-center text-lg text-primary sm:flex">
        <Link
          href="/"
          className={`mr-10 hover:text-info ${activeTab === "/" ? "text-secondary" : ""}`}
        >
          Home
        </Link>
        <Link
          href="/datasets"
          className={`mr-10 hover:text-info ${activeTab.includes("datasets") ? "text-secondary" : ""}`}
        >
          Datasets
        </Link>
        <Link
          href="/about"
          className={`mr-10 hover:text-info ${activeTab === "/about" ? "text-secondary" : ""}`}
        >
          About
        </Link>
        {isAuthenticated && <FontAwesomeIcon icon={faUser} />}
        {isAuthenticated && <span>{username()}</span>}
        {!isAuthenticated && (
          <button
            className="rounded border-2 bg-secondary px-4 py-2 text-sm font-bold text-white hover:border-2 hover:border-secondary hover:bg-transparent hover:text-secondary"
            onClick={login}
          >
            <FontAwesomeIcon icon={faRightToBracket} /> Sign In
          </button>
        )}
        {isAuthenticated && (
          <button onClick={logout}>
            <FontAwesomeIcon icon={faRightFromBracket} />
          </button>
        )}
      </div>
      <div className="relative sm:hidden">
        <button
          onClick={() => setIsMenuOpen(!isMenuOpen)}
          className="text-primary focus:outline-none"
        >
          <FontAwesomeIcon icon={faBars} />
        </button>
        {isMenuOpen && (
          <div className="absolute right-0 mt-2 w-48 origin-top-right rounded-md bg-white shadow-lg">
            <Link
              href="/"
              className="block px-4 py-2 text-primary hover:bg-secondary hover:text-white"
            >
              Home
            </Link>
            <Link
              href="/datasets"
              className="block px-4 py-2 text-primary hover:bg-secondary hover:text-white"
            >
              Datasets
            </Link>
            <Link
              href="/about"
              className="block px-4 py-2 text-primary hover:bg-secondary hover:text-white"
            >
              About
            </Link>
            {isAuthenticated && (
              <div className="border-b border-gray-200 px-4 py-2">
                <FontAwesomeIcon icon={faUser} className="mr-2" />
                {username()}
              </div>
            )}
            {!isAuthenticated && (
              <button
                onClick={login}
                className="block w-full px-4 py-2 text-left text-primary hover:bg-secondary hover:text-white"
              >
                <FontAwesomeIcon icon={faRightToBracket} className="mr-2" />
                Login
              </button>
            )}
            {isAuthenticated && (
              <button
                onClick={logout}
                className="block w-full px-4 py-2 text-left text-primary hover:bg-secondary hover:text-white"
              >
                <FontAwesomeIcon icon={faRightFromBracket} className="mr-2" />
                Logout
              </button>
            )}
          </div>
        )}
      </div>
    </div>
  );
}

export default Header;
