// src/components/Search.tsx
// SPDX-FileCopyrightText: 2024 PNED G.I.E.
//
// SPDX-License-Identifier: Apache-2.0

"use client";

import { useState } from "react";
import { useRouter } from "next/navigation";
import { searchDatasets, SearchResult } from "@/services/ckan/search";
import { FiSearch } from "react-icons/fi";

const debounce = <F extends (...args: any[]) => any>(
  fn: F,
  delay: number,
): ((...args: Parameters<F>) => void) => {
  let timeoutId: ReturnType<typeof setTimeout> | null = null;
  return function (...args: Parameters<F>) {
    if (timeoutId) {
      clearTimeout(timeoutId);
    }
    timeoutId = setTimeout(() => fn(...args), delay);
  };
};

export const Search = () => {
  const [searchTerm, setSearchTerm] = useState<string>("");
  const [searchResults, setSearchResults] = useState<SearchResult[]>([]);
  const router = useRouter();

  const fetchSuggestions = async (term: string) => {
    if (term.trim()) {
      try {
        const results = await searchDatasets(term);
        setSearchResults(results);
      } catch (error) {
        console.error("Error fetching suggestions:", error);
        setSearchResults([]);
      }
    } else {
      setSearchResults([]);
    }
  };

  const debouncedFetchSuggestions = debounce(fetchSuggestions, 300);

  const handleSearchChange = (event: React.ChangeEvent<HTMLInputElement>) => {
    const term = event.target.value;
    setSearchTerm(term);
    debouncedFetchSuggestions(term);
  };

  const handleSelectSuggestion = (suggestion: SearchResult) => {
    router.push(`/datasets/${suggestion.id}`);
  };

  const handleSubmit = (event: React.FormEvent<HTMLFormElement>) => {
    event.preventDefault();
    if (!searchTerm.trim()) return;
    router.push(`/search?term=${encodeURIComponent(searchTerm)}`);
  };

  return (
    <div className="my-6 w-full">
      <form className="flex" onSubmit={handleSubmit}>
        <input
          className="flex-grow border-2 border-r-0 border-primary p-4 text-lg focus:border-primary focus:outline-none"
          type="search"
          value={searchTerm}
          onChange={handleSearchChange}
          placeholder="Search datasets..."
          name="search"
          autoComplete="on"
        />
        <button
          type="submit"
          className="flex items-center justify-center bg-secondary p-4 text-white"
        >
          <FiSearch size="20px" />
        </button>
      </form>
      {searchResults.length > 0 && (
        <ul className="mt-2 border border-gray-300">
          {searchResults.map((result) => (
            <li
              key={result.id}
              className="cursor-pointer p-2 hover:bg-warning"
              onClick={() => handleSelectSuggestion(result)}
            >
              {result.title}
            </li>
          ))}
        </ul>
      )}
    </div>
  );
};

// src/app/components/search/search.component.ts
// SPDX-FileCopyrightText: 2024 Stichting Health-RI
// SPDX-FileContributor: PNED G.I.E.
//
// SPDX-License-Identifier: Apache-2.0

import { Component } from '@angular/core';
import { Observable, of, map } from 'rxjs';
import { catchError, debounceTime, distinctUntilChanged } from 'rxjs/operators';
import { CkanService } from '../../services/ckan.service';
import { Router } from '@angular/router';

@Component({
  selector: 'app-search',
  templateUrl: './search.component.html',
  styleUrls: ['./search.component.scss'],
})
export class SearchComponent {
  searchResults$: Observable<any[]> | undefined;
  searchTerm: string = '';

  constructor(
    private ckanService: CkanService,
    private router: Router,
  ) {}

  onSearch(event: Event): void {
    const inputValue = (event.target as HTMLInputElement).value;
    this.searchResults$ = this.ckanService.searchDatasets(inputValue).pipe(
      map((response) => response.results),
      debounceTime(300),
      distinctUntilChanged(),
      catchError((error) => {
        console.error(error);
        return of([]);
      }),
    );
  }

  onSubmit(): void {
    if (this.searchTerm) {
      this.router.navigate(['/datasets'], { queryParams: { query: this.searchTerm } });
    }
  }

  onSelectItem(item: any): void {
    const itemId = item.id;
    this.searchTerm = '';
    this.router.navigate(['/datasets', itemId]);
  }

  resetSearchInput(): void {}
}

<!--
SPDX-FileCopyrightText: 2024 Stichting Health-RI
SPDX-FileContributor: PNED G.I.E.

SPDX-License-Identifier: Apache-2.0
-->

<div class="flex justify-center p-5">
  <div class="w-full max-w-xl">
    <form class="flex items-center border-gray-300" (ngSubmit)="onSubmit()">
      <div class="relative flex-grow">
        <mat-form-field class="w-full" appearance="fill">
          <mat-label>Search</mat-label>
          <input
            matInput
            [(ngModel)]="searchTerm"
            placeholder="Search"
            (input)="onSearch($event)"
            [matAutocomplete]="auto"
            name="search"
          />
          <button
            mat-icon-button
            matSuffix
            (click)="onSubmit()"
            class="absolute inset-y-0 right-0 flex items-center px-2 bg-blue-500 text-white"
          >
            <mat-icon>search</mat-icon>
          </button>
        </mat-form-field>
      </div>
    </form>

    <mat-autocomplete
      class="autocomplete"
      (optionSelected)="onSelectItem($event.option.value)"
      #auto="matAutocomplete"
    >
      <mat-option *ngFor="let item of searchResults$ | async" [value]="item">
        <span class="title font-bold text-gray-800">{{ item.title }}</span>
        <br />
        <span class="description text-sm text-gray-600">{{
          item.description
        }}</span>
      </mat-option>
    </mat-autocomplete>
  </div>
</div>
